name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: 'Breaking changes'
    labels:
      - 'breaking-change'
      - 'breaking'
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: 'Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Chores'
    labels:
      - 'chore'
      - 'maintenance'

change-template: '- $TITLE (#$NUMBER)'
no-changes-template: '- No changes.'

autolabeler:
  - label: 'feat'
    title:
      - '/^feat/i'
  - label: 'fix'
    title:
      - '/^fix/i'
  - label: 'chore'
    title:
      - '/^chore/i'
  - label: 'breaking-change'
    body:
      - 'BREAKING CHANGE'

commitish-template: main

template: |
  ## What’s Changed

  $CHANGES
